// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzOnM21gbtdGvQe13_0Xx9kOZZA9eCR-k',
    appId: '1:299952800021:web:dc74a7ffd93dd2818da91c',
    messagingSenderId: '299952800021',
    projectId: 'mynew-roject',
    authDomain: 'mynew-roject.firebaseapp.com',
    storageBucket: 'mynew-roject.appspot.com',
    measurementId: 'G-BWFBJ466YY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB82m2AT9f57jGImFX15WO5MW8AM7HiTvY',
    appId: '1:299952800021:android:9acacb3c53ff0f448da91c',
    messagingSenderId: '299952800021',
    projectId: 'mynew-roject',
    storageBucket: 'mynew-roject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7pRDLjsE5gn_xJps0jx350fmPAx8wl2g',
    appId: '1:299952800021:ios:31589b6ecb89eab08da91c',
    messagingSenderId: '299952800021',
    projectId: 'mynew-roject',
    storageBucket: 'mynew-roject.appspot.com',
    iosClientId: '299952800021-16og7p990u3j0tm8thlcuvqodq8m68fr.apps.googleusercontent.com',
    iosBundleId: 'com.example.myNewProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7pRDLjsE5gn_xJps0jx350fmPAx8wl2g',
    appId: '1:299952800021:ios:31589b6ecb89eab08da91c',
    messagingSenderId: '299952800021',
    projectId: 'mynew-roject',
    storageBucket: 'mynew-roject.appspot.com',
    iosClientId: '299952800021-16og7p990u3j0tm8thlcuvqodq8m68fr.apps.googleusercontent.com',
    iosBundleId: 'com.example.myNewProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzOnM21gbtdGvQe13_0Xx9kOZZA9eCR-k',
    appId: '1:299952800021:web:bd8c63c452ca54628da91c',
    messagingSenderId: '299952800021',
    projectId: 'mynew-roject',
    authDomain: 'mynew-roject.firebaseapp.com',
    storageBucket: 'mynew-roject.appspot.com',
    measurementId: 'G-4ZT7XJYDMK',
  );
}
